name: Release Deployment
on:
  push:
    branches: ["main"]

jobs:
  docker-release:
    name: Tagged Docker release to Google Artifact Registry
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
        with:
          token: '${{ secrets.ALCHEMIST_PAT }}'
          submodules: 'true'

      - id: auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2.0.1
        with:
          credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}'
          token_format: 'access_token'

      - name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: us-west2-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Get tag
        id: get-tag
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - id: docker-push-tagged
        name: Tag Docker image and push to Google Artifact Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            us-west2-docker.pkg.dev/alchemist-410607/elixr-user-service/elixr-user-service:latest

      - id: cloud-run-deploy
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: 'elixr-user-service'
          image: 'us-west2-docker.pkg.dev/alchemist-410607/elixr-user-service/elixr-user-service:latest'